version: '3.9'

services:

  kali:
    container_name: kali
    image: kali
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /bin/bash
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /opt/kali/home:/home

